In [22]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.preprocessing import LabelEncoder
import numpy as np

In [23]:
df=pd.read_csv('./Datasets/Iris.csv')

In [24]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [25]:
le=LabelEncoder()
df['Species']=le.fit_transform(df['Species'])

In [26]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1            5.1           3.5            1.4           0.2        0
1   2            4.9           3.0            1.4           0.2        0
2   3            4.7           3.2            1.3           0.2        0
3   4            4.6           3.1            1.5           0.2        0
4   5            5.0           3.6            1.4           0.2        0

In [27]:
df=df[['SepalLengthCm','PetalLengthCm','Species']]

In [28]:
df.head()

   SepalLengthCm  PetalLengthCm  Species
0            5.1            1.4        0
1            4.9            1.4        0
2            4.7            1.3        0
3            4.6            1.5        0
4            5.0            1.4        0

In [29]:
X_train,X_test,y_train,y_test=train_test_split(df.drop(columns='Species'),df.iloc[:,-1],test_size=0.2,random_state=42)

In [30]:
X_train.head()

    SepalLengthCm  PetalLengthCm
22            4.6            1.0
15            5.7            1.5
65            6.7            4.4
11            4.8            1.6
42            4.4            1.3

In [31]:
model=LogisticRegression(multi_class='multinomial')
model.fit(X_train,y_train)
y_predict=model.predict(X_test)

c:\Users\anush\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

In [32]:
print(f"The accuracy score is {accuracy_score(y_test,y_predict)}")

The accuracy score is 1.0

In [33]:
pd.DataFrame(confusion_matrix(y_test,y_predict),columns=list(range(0,3)))

    0  1   2
0  10  0   0
1   0  9   0
2   0  0  11

In [36]:
query=np.array([[3.4,2.7]])
model.predict_proba(query)

c:\Users\anush\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([[8.09965681e-01, 1.89436112e-01, 5.98206953e-04]])

In [37]:
model.predict(query)

c:\Users\anush\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([0])