In [19]:
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import seaborn as sns
from sklearn.metrics import accuracy_score

In [20]:
df=pd.read_csv('../Datasets/heart.csv')

In [21]:
df.shape

(303, 14)

In [22]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [23]:
X_train,X_test,y_train,y_test=train_test_split(df.drop(columns='target'),df.iloc[:,-1],test_size=0.2,random_state=42)

In [24]:
X_train.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
132,42,1,1,120,295,0,1,162,0,0.0,2,0,2
202,58,1,0,150,270,0,0,111,1,0.8,2,0,3
196,46,1,2,150,231,0,1,147,0,3.6,1,0,2
75,55,0,1,135,250,0,0,161,0,1.4,1,0,2
176,60,1,0,117,230,1,1,160,1,1.4,2,2,3

In [25]:
rf=RandomForestClassifier()
rf.fit(X_train,y_train)

RandomForestClassifier()

In [26]:
y_pred=rf.predict(X_test)
accuracy_score(y_test,y_pred)

0.8524590163934426

In [27]:
rf=RandomForestClassifier(max_samples=0.75,random_state=42)
rf.fit(X_train,y_train)

RandomForestClassifier(max_samples=0.75, random_state=42)

In [28]:
y_pred=rf.predict(X_test)
accuracy_score(y_test,y_pred)

0.9016393442622951

### Tuning Hyperparameters

In [29]:
n_estimators=[20,100,160,200]
max_features=[0.2,0.6,1.0]
max_depth=[2,8,None]
max_samples=[0.5,0.75,1.0]

In [30]:
param_grid={
    'n_estimators':n_estimators,
    'max_features':max_features,
    'max_depth':max_depth,
    'max_samples':max_samples
}
print(param_grid)

{'n_estimators': [20, 100, 160, 200], 'max_features': [0.2, 0.6, 1.0], 'max_depth': [2, 8, None], 'max_samples': [0.5, 0.75, 1.0]}

In [31]:
rf_grid=RandomForestClassifier()

In [32]:
from sklearn.model_selection import GridSearchCV
search=GridSearchCV(
                estimator=rf_grid,
                param_grid=param_grid,
                cv=5,
                verbose=2,
                n_jobs=-1
)

In [33]:
search.fit(X_train,y_train)

Fitting 5 folds for each of 108 candidates, totalling 540 fits

GridSearchCV(cv=5, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'max_depth': [2, 8, None],
                         'max_features': [0.2, 0.6, 1.0],
                         'max_samples': [0.5, 0.75, 1.0],
                         'n_estimators': [20, 100, 160, 200]},
             verbose=2)

In [34]:
search.best_params_

{'max_depth': 2, 'max_features': 0.2, 'max_samples': 0.75, 'n_estimators': 20}

In [35]:
search.best_score_

0.8386054421768708

### RandomSearch cv

In [36]:
n_estimators=[20,100,160,200]
max_features=[0.2,0.6,1.0]
max_depth=[2,8,None]
max_samples=[0.5,0.75,1.0]
bootstrap = [True,False]
min_samples_split = [2, 5]
min_samples_leaf = [1, 2]

In [37]:
param_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
              'max_samples':max_samples,
              'bootstrap':bootstrap,
              'min_samples_split':min_samples_split,
              'min_samples_leaf':min_samples_leaf
             }
print(param_grid)

{'n_estimators': [20, 100, 160, 200], 'max_features': [0.2, 0.6, 1.0], 'max_depth': [2, 8, None], 'max_samples': [0.5, 0.75, 1.0], 'bootstrap': [True, False], 'min_samples_split': [2, 5], 'min_samples_leaf': [1, 2]}

In [38]:
from sklearn.model_selection import RandomizedSearchCV

In [39]:
search_random=RandomizedSearchCV(
    estimator=rf_grid,
    cv=5,
    param_distributions=param_grid,
    verbose=2,
    n_jobs=-1
)

In [40]:
search_random.fit(X_train,y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits

c:\Users\anush\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:540: FitFailedWarning:
30 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
30 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\anush\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\anush\anaconda3\Lib\site-packages\sklearn\base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\anush\anaconda3\Lib\site-packages\sklearn\ensemble\_forest.py", line 433, in fit
    raise ValueError(
ValueError: `max_sample` cannot be set if `bootstrap=False`. Either switch to `bootstrap=True` or set `max_sample=None`.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
c:\Users\anush\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:1102: UserWarning: One or more of the test scores are non-finite: [0.80986395        nan 0.82202381        nan        nan        nan
        nan 0.80578231 0.81811224        nan]
  warnings.warn(

RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(), n_jobs=-1,
                   param_distributions={'bootstrap': [True, False],
                                        'max_depth': [2, 8, None],
                                        'max_features': [0.2, 0.6, 1.0],
                                        'max_samples': [0.5, 0.75, 1.0],
                                        'min_samples_leaf': [1, 2],
                                        'min_samples_split': [2, 5],
                                        'n_estimators': [20, 100, 160, 200]},
                   verbose=2)

In [41]:
search_random.best_params_

{'n_estimators': 100,
 'min_samples_split': 2,
 'min_samples_leaf': 2,
 'max_samples': 0.75,
 'max_features': 0.2,
 'max_depth': None,
 'bootstrap': True}

In [42]:
search_random.best_score_

0.8220238095238095